### ISSUE TITLE
No dir for jvmti-agent-base error

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel-packaging#188]
Building mandrel fails:

```
$ java -ea ../mandrel-packaging/build.java --mx-home /opt/mx --mandrel-repo .
...
Exception in thread "main" java.lang.IllegalArgumentException: There is no existing dir for record jvmti-agent-base
	at PathFinder.getFirstExisting(build.java:1079)
	at build.lambda$main$0(build.java:83)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at build.main(build.java:81)
```

**Comment by galderz** [comment]
Seems related to the changes in https://github.com/graalvm/mandrel-packaging/commit/cfe4c762d33154d50575eb3bba89962f72c45e19. Am I missing some parameter to make this work @zakkak?

**Comment by galderz** [comment]
Worked around this by passing in `--skip-native-agents` and patching:

```
diff --git a/build.java b/build.java
index 7083cde..03732fd 100644
--- a/build.java
+++ b/build.java
@@ -1091,10 +1091,10 @@ class Maven
         , "compiler"
         , "objectfile"
         , "svm-driver"
-        , "jvmti-agent-base"
+       //        , "jvmti-agent-base"
         , "svm-agent"
-        , "svm-diagnostics-agent"
-        , "svm-configure"
+       //        , "svm-diagnostics-agent"
+       //        , "svm-configure"
     );
```

**Comment by zakkak** [comment]
@galderz can you please post the mandrel-packaging version, graal version, and openJDK version?

**Comment by galderz** [comment]
mandrel-packaging: `mandrel-21.2.0.1-Final-1` tag
graal version: https://github.com/graalvm/mandrel/tree/mandrel/21.2
jdk version:
```
❯ java --version
openjdk 11.0.13-internal 2021-10-19
OpenJDK Runtime Environment (fastdebug build 11.0.13-internal+0-adhoc.g.jdk11u-dev)
OpenJDK 64-Bit Server VM (fastdebug build 11.0.13-internal+0-adhoc.g.jdk11u-dev, mixed mode)
```

**Comment by zakkak** [comment]
`mandrel-21.2.0.1-Final-1` tag was wrong on mandrel-packaging repo. I have delete `mandrel-21.2.0.1-Final-1` both on mandrel and mandrel-packaging since we didn't actually use these tags for our release, instead we used `mandrel-21.2.0.1-Final`
