### ISSUE TITLE
build.java requires `python3` to exist

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel-packaging#217]
As pointed out by @Karm since https://github.com/graalvm/mandrel-packaging/pull/210

> Note: This now requires `python3` to exist, even on a system where python actually means Python 3 and there is no Python 2. So....I am adding
>
> ```
> mklink C:\Python39\python3.exe C:\Python39\python.exe
> ```
>
> to make it work now. Not sure if build.java shouldn't be smarter about it.

We should check if `python3` is available before setting it.

**Comment by Karm** [comment]
There is some rudimentary logic in
https://github.com/graalvm/mx/blob/master/mx.cmd
so we can expand that or make our own.

I fixed Hydra Jenkins builds and I will tend to ci.modcluster.io ones later this week....

**Comment by zakkak** [comment]
https://github.com/graalvm/mx/pull/248 does something like that, but the other way around (at least for now). It checks if `python` is present, and if not it then tries `python3`.
