### ISSUE TITLE
Branch 22.3 does not build  mandrel/22.3

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel-packaging#271]
```
DEBUG [OperatingSystem] Execute [git, apply, /home/tester/resources/truffle-api-removal.patch] in /home/tester/mandrel with environment variables []
error: can't open patch '/home/tester/resources/truffle-api-removal.patch': No such file or directory
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 128
```

Master is O.K.

Rebase?
```
pick 2a03339 Clean up dependency removals and further reduce Mandrel's dependencies
pick 383b8ae Remove llvm_supported patch as it is handled in build.java
pick f79a8db Make `git apply` work on windows as well
pick a3ee6fc CI: Trigger tests when updating patches
pick 55fc959 CI: Run tests against mandrel/22.3 branch instead of graal/master
```

Weird CI didn't catch it?

**Comment by jerboaa** [comment]
@Karm Did you try running from the `mandrel-packaging` directory? See https://github.com/graalvm/mandrel/commit/46e68bdda835b0b31841493c5bac8cf0e049b474

**Comment by Karm** [comment]
Hmm, that is a regression to how it used to work. I'll check it...

**Comment by zakkak** [comment]
> Master is O.K.

`master` builds OK but brings in more dependencies than `22.3`.

> Weird CI didn't catch it?

It did, but I worked around it in https://github.com/graalvm/mandrel/pull/426

> Hmm, that is a regression to how it used to work.

True, we could either introduce a new parameter `mandrel-packaging-repo` to point to the repository where we expect to find the patch.

FYI https://github.com/oracle/graal/pull/5002 tries to make `master` not require the patch.

**Comment by zakkak** [comment]
Closing as fixed.
