### ISSUE TITLE
Windows fails to build with 23 and master due to libchelper.lib location change

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel-packaging#346]
i.e.

Used to be:
C:\tmp\mandrel\substratevm\mxbuild\windows-amd64\com.oracle.svm.native.libchelper\amd64\libchelper.lib

It is now:

C:\tmp\mandrel\substratevm\mxbuild\windows-amd64-jdk17\com.oracle.svm.native.libchelper\amd64\libchelper.lib

**Comment by jerboaa** [comment]
Should be fixed with: https://github.com/graalvm/mandrel-packaging/pull/342 are you using latest master?

**Comment by Karm** [comment]
When I reverted the fix from #342 is has started to work for me again, the build completes and then fails to compile native agent for an unrelated reason (old VS).

**Comment by jerboaa** [comment]
NVM. We should be using the 23.0 branch for building 23.0. That tree doesn't have the change.
