### ISSUE TITLE
Revert "Set MaxRAM and MaxRAMPercentage in launcher for native-image driver" https://github.com/graalvm/mandrel-packaging/pull/366

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel-packaging#403]
Revert https://github.com/graalvm/mandrel-packaging/pull/366 if/when https://github.com/oracle/graal/pull/8384 gets merged.

**Comment by jerboaa** [comment]
https://github.com/oracle/graal/pull/8384 is merged in 24.1. It's not the 100% equivalent, but it'll probably do.
