### ISSUE TITLE
Wrong link in ` For a complete list of changes please visit ...`

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel-packaging#66]
Hello,

While producing the release, I had to alter this manually. IMHO we should be bale to parse for a number at the end of Alpha/Beta and increment that, right?  Thx for feedback.

```
- For a complete list of changes please visit https://github.com/graalvm/mandrel/compare/mandrel-20.2.0.0.Beta2...mandrel-20.2.0.1.Beta2
+For a complete list of changes please visit https://github.com/graalvm/mandrel/compare/mandrel-20.2.0.0.Beta1...mandrel-20.2.0.0.Beta2
```

**Comment by zakkak** [comment]
#66 solves the reported issue.

Regarding "IMHO we should be bale to parse for a number at the end of Alpha/Beta and increment that, right?" yes that's totally doable, it will just complicate the compareTo method (https://github.com/graalvm/mandrel-packaging/pull/67/files#diff-a4b7a1fc2c34ee3ee981fc52d4940ccae22e652bfc370057fefecf59b6cc4e08R695)

So you suggest that for pre-releases we should run `/mandrel-release.java -s Beta release` or `/mandrel-release.java -s Alpha release` and the script would automatically figure out the tag.
How would you number the first Alpha? `Alpha1` or just `Alpha`?
